name: Evaluate Submission

on:
  workflow_run:
    workflows: ["Validate Submission"]
    types:
      - completed

permissions:
  contents: read, write
  pull-requests: read

jobs:
  run_harness:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    outputs:
        results: ${{ steps.run_harness.outputs.results }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.14t
        uses: actions/setup-python@v6
        with:
          python-version: "3.14t"

      - name: Run Harness
        id: run_harness
        run: |
          python challenge/harness.py --num-trials 3 --json submissions/${{ env.PR_AUTHOR }}.py graphs | tee ${{ runner.temp }}/results.txt
          DATA=$(cat ${{ runner.temp }}/results.txt | jq -c .)
          echo "results=$DATA" >> "$GITHUB_OUTPUT"

  update_journal:
    needs: evalute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        ref: main

      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - run: |
          echo "${{ needs.run_harness.outputs.results }}" > ${{ runner.temp }}/results.txt
          python scores/format_journal_entry.py ${{ github.event.workflow_run.jobs.evaluate.outputs.pr_author }} ${{ github.event.workflow_run.jobs.evaluate.outputs.pr_url }} ${{ github.event.workflow_run.jobs.evaluate.outputs.pr_number }} ${{ runner.temp }}/results.txt >> scores/journal.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scores/journal.txt
          git commit -m "Log submission result from ${{ github.event.workflow_run.jobs.evaluate.pr_author }}"
          git push
